config/routes.rb
SemanaAmbiente::Application.routes.draw do

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}

  resources :users do
  	member do
  		get 'confirm'
  	end
  	
  	collection do
  		get 'confirm'
  	end

  	member do
  		get 'search'
  	end

  	collection do
  		get 'search'
  	end
  end

	
  resources :mesasredondas

  resources :minicursos

  resources :palestras

  get "pages/index"
  
  get "pages/programacao"

  get "pages/status"
  
  get "pages/cadastro"
  
  resources :palestrantes

  root :to => 'pages#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  belongs_to :minicurso
  attr_accessible :cpf, :institution, :name, :minicurso_id, :tipo, :status
  
  # para ficar em portugues eu mudei no en.yml
  validates_presence_of :name, :message => 'deve ser informado'  
  validates_presence_of :cpf, :message => 'deve ser informado'
  validates_presence_of :institution, :message => 'deve ser informada'
  validates_presence_of :minicurso_id, :message => 'deve ser informado'
  validates_presence_of :password, :presence => true, :on => :create, :message => 'deve ser informada'
  validates_presence_of :password_confirmation, :presence => true, :on => :create, :message => 'deve ser informada'
	validates_presence_of :tipo, :presence => true, :on => :create, :message => 'deve ser informado'     
  
  validates_numericality_of :cpf
  validates_length_of :cpf, :is => 11
  
  has_and_belongs_to_many :roles
  
  def confirm
	  	self.status = true 		
	end
	
  def role?(role)
   return !!self.roles.find_by_name(role.to_s)
 	end

	before_create :setup_role

	private

	def setup_role
		if self.role_ids.empty?
		  self.role_ids = [3]
		end
	end
	
	def self.search(search)
  	search_condition = "%" + search + "%"
  	find(:all, :conditions => ['name LIKE ? OR cpf LIKE ?', search_condition, search_condition])
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	#before_filter :authenticate_user!
	
	def search
		@users = User.search(params[:query])

    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
	end
  
  def index
    authorize! :read, @user
    #@users = User.all(:order => "name")
		#@users = User.scoped
		#@users = User.search(params[:query]) if params[:query].present?
		#@users = User.find(:all, :conditions => ['status = ?', true]) if params[:option].present?
		@users = User.scoped(:order => "name ASC", :conditions => ['tipo <> ?', 'Administrador'])
		if params[:query].present?
			@users = User.search(params[:query]) 
			@consultado = true
		end
		if params[:option].present?
			@users = User.find(:all, :order => "name ASC", 
												 :conditions => ['status = ? and tipo <> ?', true, 'Administrador']) 
			@confirmados = true
		end
		
    respond_to do |format|
      format.html # index.html.erb
			format.pdf do		    
		    pdf = Prawn::Document.new(:page_size => "A4")
		    pdf.text "Inscritos", :style => :bold, :size => 14,:spacing => 1.5, :align => :center
 		    pdf.text "Total de inscritos: #{@users.count}", :size => 10,:spacing => 1.5, :align => :right
				#da espaco entre o titulo e a tabela
				pdf.move_down(20)
				headers = ["Nome","e-mail", "Assinatura"]
				users = @users.map do |i|
					[
						i.name.titleize,
						i.email,
						" "
					]
				end

				pdf.table ([headers] + users), :row_colors => ["FFFFFF", "DDDDDD"],
				:header => true, :column_widths => {0 => 200, 1 => 180, 2 => 120} do
					style row(0), :borders => [:bottom], :background_color => "DDDDDD", :font_style => :bold
				end
				
		    send_data pdf.render, type: "application/pdf", disposition: "inline"
		    # send_data renders the pdf on the client side rather than saving it on the server filesystem.
		    # Inline disposition renders it in the browser rather than making it a file download.
	    end
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    authorize! :edit, @user
    @user = User.find(params[:id])
  end

  def confirm
    @user = User.find(params[:id])
    @user.confirm
		@user.save
    respond_to do |format|
      format.html {redirect_to users_path, notice: 'Inscricao confirmada.' }
      format.json { render json: @user }
    end
  end
  
  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        #format.html { redirect_to @user, notice: 'User was successfully created.' }
        #format.html { redirect_to root_path, notice: 'User was successfully created.' }
				format.html { redirect_to users_url, notice: 'User was successfully created.' }                
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
	<fieldset>
		<legend>Inscrição</legend>
		<div>  
			<%= f.text_field :name, :placeholder => "Nome completo" %>
		</div>

		<div>
			<%= f.text_field :cpf, :placeholder => "CPF" %>
			<span class="help-inline">(Somente números. Ex.: 99999999999)</span>
		</div>
		  
		<div>
			<%= f.text_field :institution, :placeholder => "Instituição" %>
		</div>
		
		<div>
			<%= f.email_field :email, :placeholder => "E-mail" %>
			<span class="help-inline">(Ex.: exemplo@email.com)</span>
		</div>

		<div>
			<%= f.password_field :password, :placeholder => "Senha" %>
			<span class="help-inline">(A senha deve ter no mínimo 8 caracteres)</span>
		</div>

		<div>
			<%= f.password_field :password_confirmation, :placeholder => "Confirme a senha" %>
			<span class="help-inline">(Deve ser igual a senha)</span>
		</div>
		<div><%= f.label 'Escolha um minicurso:' %><br />
			<%for m in Minicurso.all%>
				<p><%=radio_button_tag "user[minicurso_id]", m.id %>
				<%= m.title %> (n vagas restante(s))
				</p>
			<%end%>
				<p><%=radio_button_tag "user[minicurso_id]", 0, :checked => true %> Nenhum
		</div>

		<div><%= f.submit "Cadastrar", :class => "btn" %></div>
	</fieldset>
<% end %>

app/views/users/_search.html.erb
<%#= form_tag search_users_path, :method => 'get', :class => 'form-search' do %>
  <%#= text_field_tag :query, nil, :class => 'input-medium search-query' %>
  <%#= submit_tag "Procurar", :name => nil, :class => "btn" %>
<%# end %>
<%= form_tag users_path, :method => 'get', :class => 'form-search' do %>
  <%= text_field_tag :query, "", 
  		:placeholder => "busca por nome ou cpf...",
  		:size => 30,
  		:class => 'input-medium search-query' %>
  <%= submit_tag "Procurar", :name => nil, :class => "btn" %>
<% end %>

app/views/users/_search_results.html.erb
<ul>
  <% @users.each do |user| %>
  <li><%= user.name %></li>
  <% end %>
</ul>

app/views/users/confirm.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
	<fieldset>
		<legend>Confirmação de inscrição</legend>
		<div>  
			<%= @user.name %>
		</div>

		<div>
			<%= @user.cpf %>
		</div>
		  
		<div>
			<%= f.check_box :status %><%= @user.status %>
		</div>
		
		<div><%= f.submit "Confirmar", :class => "btn" %></div>
	</fieldset>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h3># Alteração de inscrito</h3>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h3>#Inscritos</h3>
</div>

<%= render :partial => 'search' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>CPF</th>
      <th>Situação</th>
      <th>Data de inscrição</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user_path(user) %></td>
        <td><%= user.cpf %></td>
        <td><%= user.status ? "Confirmado" : "Aguardando confirmação" %></td>
        <td><%= user.created_at %><%#= user.created_at.to_formatted_s(:db) %></td>
        <td>
          <%= link_to 'Confirmar',
                      confirm_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to 'Alterar',
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to 'Remover',
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => 'Deseja realmente excluir?' },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Nova inscrição",
            new_user_path,
            :class => 'btn btn-primary' %>
<% unless @confirmados %>
	<% unless @consultado %>
		<%= link_to "Imprimir",
					      users_path(:format => :pdf),
					      :class => 'btn btn-primary' %>
  <% else %>
		<%= link_to "Voltar", users_path, :class => 'btn btn-primary' %>  	
  <% end %>
<% else %>
	<%= link_to "Imprimir", 
							{ :controller=>"users", :action=>"index", :option => "confirmados", :format => :pdf },
							:class => 'btn btn-primary' %>
<% end %>

app/views/users/new.html.erb
<%- model_class = User -%>
<%= render :partial => 'form' %>

app/views/users/search.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h3>#Inscritos</h3>
</div>
<%= render :partial => 'search' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>CPF</th>
      <th>Situação</th>
      <th>Data de inscrição</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user_path(user) %></td>
        <td><%= user.cpf %></td>
        <td><%= user.status ? "Confirmado" : "Aguardando confirmação" %></td>
        <td><%= user.created_at.to_formatted_s(:db) %></td>
        <td>
          <%= link_to 'Confirmar',
                      confirm_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to 'Alterar',
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to 'Remover',
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => 'Deseja realmente excluir?' },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Nova inscrição",
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cpf) %>:</strong></dt>
  <dd><%= @user.cpf %></dd>
  <dt><strong><%= model_class.human_attribute_name(:institution) %>:</strong></dt>
  <dd><%= @user.institution %></dd>
  <dt><strong><%= model_class.human_attribute_name(:minicurso_id) %>:</strong></dt>
  <dd><%= @user.minicurso_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/users/xxsearch.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h3>#Inscritos</h3>
</div>
<%= render :partial => 'search' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>CPF</th>
      <th>Situação</th>
      <th>Data de inscrição</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user_path(user) %></td>
        <td><%= user.cpf %></td>
        <td><%= user.status ? "Confirmado" : "Aguardando confirmação" %></td>
        <td><%= user.created_at.to_formatted_s(:db) %></td>
        <td>
          <%= link_to 'Confirmar',
                      confirm_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to 'Alterar',
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to 'Remover',
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => 'Deseja realmente excluir?' },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Nova inscrição",
            new_user_path,
            :class => 'btn btn-primary' %>