config/routes.rb
SemanaAmbiente::Application.routes.draw do

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}

  resources :users do
  	member do
  		get 'confirm'
  	end
  	
  	collection do
  		get 'confirm'
  	end

  	member do
  		get 'search'
  	end

  	collection do
  		get 'search'
  	end
  end

	
  resources :mesasredondas

  resources :minicursos

  resources :palestras

  get "pages/index"
  
  get "pages/programacao"

  get "pages/status"
  
  get "pages/cadastro"
  
  resources :palestrantes

  root :to => 'pages#index'

end

app/models/palestra.rb
class Palestra < ActiveRecord::Base

  belongs_to :palestrante
  attr_accessible :data, :hora, :title, :palestrante_id

  # para ficar em portugues eu mudei no en.yml
  validates_presence_of :title, :message => 'deve ser informado'
  validates_presence_of :data, :message => 'deve ser informada'
  validates_presence_of :hora, :message => 'deve ser informado'
  validates_presence_of :palestrante_id, :message => 'deve ser informado'  
  
  validates_uniqueness_of :title
   
  validates_associated :palestrante
    
end

app/controllers/palestras_controller.rb
class PalestrasController < ApplicationController

	before_filter :authenticate_user!,:except => [:index, :show] 
  # GET /palestras
  # GET /palestras.json
  def index
		#@palestrante = Palestrante.new
    @palestras = Palestra.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @palestras }
    end
  end

  # GET /palestras/1
  # GET /palestras/1.json
  def show
    @palestra = Palestra.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @palestra }
    end
  end

  # GET /palestras/new
  # GET /palestras/new.json
  def new
    authorize! :new, @palestra
    @palestra = Palestra.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @palestra }
    end
  end

  # GET /palestras/1/edit
  def edit
    authorize! :edit, @palestra
    @palestra = Palestra.find(params[:id])
  end

  # POST /palestras
  # POST /palestras.json
  def create
    authorize! :create, @palestra
    @palestra = Palestra.new(params[:palestra])

    respond_to do |format|
      if @palestra.save
        format.html { redirect_to @palestra, notice: 'Palestra cadastrada com sucesso.' }
        format.json { render json: @palestra, status: :created, location: @palestra }
      else
        format.html { render action: "new" }
        format.json { render json: @palestra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /palestras/1
  # PUT /palestras/1.json
  def update
		authorize! :update, @palestra
    @palestra = Palestra.find(params[:id])

    respond_to do |format|
      if @palestra.update_attributes(params[:palestra])
        format.html { redirect_to @palestra, notice: 'Palestra modificada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @palestra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /palestras/1
  # DELETE /palestras/1.json
  def destroy
		authorize! :destroy, @palestra
    @palestra = Palestra.find(params[:id])
    @palestra.destroy

    respond_to do |format|
      format.html { redirect_to palestras_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/palestras_helper.rb
module PalestrasHelper
end

app/views/palestras/_form.html.erb
<%= form_for @palestra, :html => { :class => 'form-horizontal' } do |f| %>

  <% if @palestra.errors.any? %>
    <div id="error_explanation">
      <h2>
      	<% if @palestra.errors.count > 1 %>
	      	<%= pluralize(@palestra.errors.count, "erro") %> impediram que esta palestra fosse cadastrada:
	      <% else %>	
		      <%= pluralize(@palestra.errors.count, "erro") %> impediu que esta palestra fosse cadastrada:
	      <% end %>
    	</h2>

      <ul>
      <% @palestra.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="control-group">
    <%= f.label 'Título', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Data', :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :data, :class => 'date_select', :order => [:day, :month, :year], :prompt => { :day => 'Selecione o dia', :month => 'Selecione o mês', :year => 'Selecione o ano'}, :use_month_names => ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'] %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Horário', :class => 'control-label' %>
    <div class="controls">
      <%= f.time_select :hora, :class => 'time_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Palestrante', :class => 'control-label' %>
    <div class="controls">
      <%= collection_select(:palestra, :palestrante_id, Palestrante.all, :id, :name, {:prompt => "Escolha um palestrante"}) %>
		  <!-- Button to trigger modal -->
			<a data-target="#modalPalestrante" role="button" class="btn btn-success" href="/palestrantes/new" data-toggle="modal">+</a>
    </div>
  </div>
  
	<!-- Modal -->
	<div id="modalPalestrante" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h3 id="myModalLabel">Novo palestrante</h3>
		</div>
		<div class="modal-body">
			<!-- conteudo aqui -->
		</div>
		<div class="modal-footer">
			<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
		</div>
	</div>

  <div class="form-actions">
    <%= f.submit 'Cadastrar', :class => 'btn btn-primary' %>
    <%= link_to 'Cancelar',
                palestras_path, :class => 'btn' %>
  </div>
<% end %>

app/views/palestras/edit.html.erb
<%- model_class = Palestra -%>
<div class="page-header">
  <h3>Alterando palestra</h3>
</div>
<%= render :partial => 'form' %>

app/views/palestras/index.html.erb
<%- model_class = Palestra -%>
<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human.pluralize %></h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Título</th>
      <th>Data</th>
      <th>Horário</th>
      <th>Palestrante</th>
      <% if can? :manage, @palestra %>
	      <th>Ações</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @palestras.each do |palestra| %>
      <tr>
        <td><%= link_to palestra.title, palestra_path(palestra) %></td>
        <td><%= palestra.data.to_s %></td>
        <td><%= palestra.hora.to_s(:time) %></td>
        <td><%= palestra.palestrante.name %></td>
	      <% if can? :manage, @palestra %>
		      <td>
		        <%= link_to 'Alterar',
		                    edit_palestra_path(palestra), :class => 'btn btn-mini' %>
		        <%= link_to 'Remover',
		                    palestra_path(palestra),
		                    :method => :delete,
		                    :data => { :confirm => 'Deseja realmente excluir?' },
		                    :class => 'btn btn-mini btn-danger' %>
		      </td>
				<% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% if can? :manage, @palestra %>
	<%= link_to 'Nova palestra',
		          new_palestra_path,
		          :class => 'btn btn-primary' %>
<% end %>

app/views/palestras/new.html.erb
<%- model_class = Palestra -%>
<div class="page-header">
  <h3>Cadastro de palestra</h3>
</div>
<%= render :partial => 'form' %>

app/views/palestras/show.html.erb
<%- model_class = Palestra -%>
<div class="page-header">
  <h3><%= @palestra.title %></h3>
</div>

<dl class="dl-horizontal">
  <dt>Data:</strong></dt>
  <dd><%= @palestra.data.to_s %></dd>
  <dt><strong>Hora:</strong></dt>
  <dd><%= @palestra.hora.to_s(:time) %></dd>
  <dt><strong>Palestrante:</strong></dt>
  <dd><%= @palestra.palestrante.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to 'Alterar',
              edit_palestra_path(@palestra), :class => 'btn' %>
  <%= link_to 'Remover',
              palestra_path(@palestra),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
	<%= link_to 'Voltar',
              palestras_path, :class => 'btn'  %>
</div>