config/routes.rb
SemanaAmbiente::Application.routes.draw do

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}

  resources :users do
  	member do
  		get 'confirm'
  	end
  	
  	collection do
  		get 'confirm'
  	end

  	member do
  		get 'search'
  	end

  	collection do
  		get 'search'
  	end
  end

	
  resources :mesasredondas

  resources :minicursos

  resources :palestras

  get "pages/index"
  
  get "pages/programacao"

  get "pages/status"
  
  get "pages/cadastro"
  
  resources :palestrantes

  root :to => 'pages#index'

end

app/models/palestrante.rb
class Palestrante < ActiveRecord::Base
  attr_accessible :institution, :lattes, :name
  
  has_many :palestras
  has_many :minicursos
  has_many :mesasredondas
	
	# para ficar em portugues eu mudei no en.yml
  validates_presence_of :name, :message => 'deve ser informado'
  validates_presence_of :institution, :message => 'deve ser informada'
  
end

app/controllers/palestrantes_controller.rb
class PalestrantesController < ApplicationController

	before_filter :authenticate_user!,:except => [:index, :show] 
  # GET /palestrantes
  # GET /palestrantes.json
  def index
    @palestrantes = Palestrante.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @palestrantes }
    end
  end

  # GET /palestrantes/1
  # GET /palestrantes/1.json
  def show
    @palestrante = Palestrante.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @palestrante }
    end
  end

  # GET /palestrantes/new
  # GET /palestrantes/new.json
  def new
  	authorize! :new, @palestrante
    @palestrante = Palestrante.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @palestrante }
    end
  end

  # GET /palestrantes/1/edit
  def edit
  	authorize! :edit, @palestrante
    @palestrante = Palestrante.find(params[:id])
  end

  # POST /palestrantes
  # POST /palestrantes.json
  def create
  	authorize! :create, @palestrante
    @palestrante = Palestrante.new(params[:palestrante])

    respond_to do |format|
      if @palestrante.save
        format.html { redirect_to @palestrante, :flash => { :notice => "Palestrante cadastrado com sucesso!"} }
        format.json { render json: @palestrante, status: :created, location: @palestrante }
      else
        format.html { render action: "new" }
        format.json { render json: @palestrante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /palestrantes/1
  # PUT /palestrantes/1.json
  def update
  	authorize! :update, @palestrante
    @palestrante = Palestrante.find(params[:id])

    respond_to do |format|
      if @palestrante.update_attributes(params[:palestrante])
        format.html { redirect_to @palestrante, notice: 'Palestrante alterado com sucesso!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @palestrante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /palestrantes/1
  # DELETE /palestrantes/1.json
  def destroy
  	authorize! :destroy, @palestrante
    @palestrante = Palestrante.find(params[:id])
    @palestrante.destroy

    respond_to do |format|
      format.html { redirect_to palestrantes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/palestrantes_helper.rb
module PalestrantesHelper
end

app/views/palestrantes/_form.html.erb
<%= form_for @palestrante, :html => { :class => 'form-horizontal' } do |f| %>

  <% if @palestrante.errors.any? %>
    <div id="error_explanation">
      <h2>
      	<% if @palestrante.errors.count > 1 %>
	      	<%= pluralize(@palestrante.errors.count, "erro") %> impediram que este palestrante fosse cadastrado:
	      <% else %>	
		      <%= pluralize(@palestrante.errors.count, "erro") %> impediu que este palestrante fosse cadastrado:
	      <% end %>
    	</h2>

      <ul>
      <% @palestrante.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="control-group">
    <%= f.label 'Nome completo', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Instituição', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :institution, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :lattes, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lattes, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Cadastrar', :class => 'btn btn-primary' %>
    <%= link_to 'Cancelar',
                palestrantes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/palestrantes/edit.html.erb
<%- model_class = Palestrante -%>
<div class="page-header">
  <h3>Alteração de plalestrante</h3>
</div>
<%= render :partial => 'form' %>

app/views/palestrantes/index.html.erb
<%- model_class = Palestrante -%>
<div class="page-header">
  <h3>#<%=t '.title', :default => model_class.model_name.human.pluralize %></h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Instituição</th>
      <th>Currículo lattes</th>
      <% if can? :create, @palestrante %>
	      <th>Ações</th>
  		<% end %>
    </tr>
  </thead>
  <tbody>
    <% @palestrantes.each do |palestrante| %>
      <tr>
        <td><%= link_to palestrante.name, palestrante_path(palestrante) %></td>
        <td><%= palestrante.institution %></td>
        <td><%= palestrante.lattes %></td>
				<% if can? :create, @palestrante %>
		      <td>
		        <%= link_to 'Alterar',
		                    edit_palestrante_path(palestrante), :class => 'btn btn-mini' %>
		        <%= link_to 'Remover',
		                    palestrante_path(palestrante),
		                    :method => :delete,
		                    :data => { :confirm => 'Deseja realmente excluir?' },
		                    :class => 'btn btn-mini btn-danger' %>
		      </td>
				<% end %>	
      </tr>
    <% end %>
  </tbody>
</table>
<% if can? :create, @palestrante %>
	<%= link_to 'Novo palestrante',
		          new_palestrante_path,
		          :class => 'btn btn-primary' %>
<% end %>

app/views/palestrantes/modal.html.erb
<div class="page-header">
  <h3>Cadastro Modal de palestrante</h3>
</div>
<%= form_for @palestrante, :html => { :class => 'form-horizontal', :remote => true } do |f| %>

  <% if @palestrante.errors.any? %>
    <div id="error_explanation">
      <h2>
      	<% if @palestrante.errors.count > 1 %>
	      	<%= pluralize(@palestrante.errors.count, "erro") %> impediram que este palestrante fosse cadastrado:
	      <% else %>	
		      <%= pluralize(@palestrante.errors.count, "erro") %> impediu que este palestrante fosse cadastrado:
	      <% end %>
    	</h2>

      <ul>
      <% @palestrante.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="control-group">
    <%= f.label 'Nome completo', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Instituição', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :institution, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :lattes, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lattes, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Cadastrar', :class => 'btn btn-primary' %>
    <%= link_to 'Cancelar',
                palestrantes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/palestrantes/new.html.erb
<%- model_class = Palestrante -%>
<div class="page-header">
  <h3>Cadastro de palestrante</h3>
</div>
<%= render :partial => 'form' %>

app/views/palestrantes/show.html.erb
<%- model_class = Palestrante -%>
<div class="page-header">
  <h3><%= @palestrante.name %></h3>
</div>

<dl class="dl-horizontal">
  <dt><strong>Instituição:</strong></dt>
  <dd><%= @palestrante.institution %></dd>
  <dt><strong>currículo lattes:</strong></dt>
  <dd><%= @palestrante.lattes %></dd>
</dl>
<% if can? :create, @palestrante %>
	<div class="form-actions">
		<%= link_to 'Alterar',
		            edit_palestrante_path(@palestrante), :class => 'btn' %>
		<%= link_to 'Remover',
		            palestrante_path(@palestrante),
		            :method => 'delete',
		            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
		            :class => 'btn btn-danger' %>
		<%= link_to 'Voltar',
		            palestrantes_path, :class => 'btn'  %>
	</div>
<% end %>