config/routes.rb
SemanaAmbiente::Application.routes.draw do

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}

  resources :users do
  	member do
  		get 'confirm'
  	end
  	
  	collection do
  		get 'confirm'
  	end

  	member do
  		get 'search'
  	end

  	collection do
  		get 'search'
  	end
  end

	
  resources :mesasredondas

  resources :minicursos

  resources :palestras

  get "pages/index"
  
  get "pages/programacao"

  get "pages/status"
  
  get "pages/cadastro"
  
  resources :palestrantes

  root :to => 'pages#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>II Semana de Meio Ambiente</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
	  <%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= javascript_include_tag "autocomplete-rails.js" %>
  	<%= csrf_meta_tags %>
  </head>

  <body>
    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#"></a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><%= link_to 'Home', root_path %></li>
							<% if can? :create, [@palestrante,@palestra,@minicurso,@mesasredonda]  %>
								<li class="dropdown">
			          	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Cadastros<b class="caret"></b></a>
			            <ul class="dropdown-menu">
					          	<li><%= link_to 'Palestrante', new_palestrante_path %></li>
			 	              <li><%= link_to 'Palestras', new_palestra_path %></li>
					          	<li><%= link_to 'Minicursos', new_minicurso_path %></li>
						          <li><%= link_to 'Mesas redondas', new_mesasredonda_path %></li>
		 	            </ul>  
			          </li>            	
							<% end %>
              <li class="dropdown">
              	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Programação<b class="caret"></b></a>
                <ul class="dropdown-menu">
	              	<li><%= link_to 'Pogramação completa', pages_programacao_path %></li>
   	              <li><%= link_to 'Palestras', palestras_path %></li>
		              <li><%= link_to 'Minicursos', minicursos_path %></li>
		              <li><%= link_to 'Mesas redondas', mesasredondas_path %></li>
   	            </ul>  
              </li>
              <li><%= link_to 'Palestrantes', palestrantes_path%></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Inscrição <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <% if user_signed_in? %>
										<li><%= link_to 'Alterar dados', edit_user_registration_path %></li>		
									<% else %>	
	                  <li><%= link_to 'Inscreva-se', new_user_registration_path %></li>
	                <% end %>  
                  <li class="divider"></li>
                  <% if user_signed_in? %>
                  	<li><%= link_to 'Consultar inscrição', pages_status_path %></li>
                  <% else %>	
                  	<li><%= link_to 'Consultar inscrição', new_user_session_path %></li>
                  <% end %>
                </ul>
              </li>
							<% if can? :create, [@palestrante,@palestra,@minicurso,@mesasredonda]  %>
								<li class="dropdown">
		           		<a href="#" class="dropdown-toggle" data-toggle="dropdown">Relatórios<b class="caret"></b></a>
		              <ul class="dropdown-menu">
				            <li><%= link_to 'Inscritos', users_path%></li>
		  		          <li>
		  		          	<%= link_to "Confirmados", 
		  		          							{ :controller=>"users", :action=>"index", :option => "confirmados" } %>
		  		          </li>
		  		          <%for m in Minicurso.all%>
						          <li>
		    				      	<%= link_to "Minicurso: #{m.title}", 
		    				      							{ :controller=>"minicursos", :action=>"index", :id => m.id } %>
		          				</li>
										<% end %>
		  						</ul>
								</li>
							<% end %>
              <li>
              	<% if user_signed_in? %>
                	<%= link_to('Sair', destroy_user_session_path, :method => 'delete') %>
                <% end %>
							</li>
            </ul>
            <%= form_for "user", :url => user_session_path, :html => { :class => "navbar-form pull-right"} do |f| %>
							<%= f.text_field :email, :id => "user_email", :class => "span2", :placeholder => "e-mail" %>
							<%= f.password_field :password, :id => "user_password", :class => "span2", :placeholder => "senha" %>
							<%= f.submit 'Ok', :class => "btn" %>
						<% end %>
            <%#= render "devise/sessions/login" %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">

				<% flash.each do |name, msg| %>
					<% if msg.is_a?(String) %>
						<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
							<a class="close" data-dismiss="alert">&#215;</a>
							<%= content_tag :div, msg, :id => "flash_#{name}" %>
						</div>
					<% end %>
				<% end %>
				
				<%= yield %>
      </div>
      <hr>

		  <div id=”rodape”>
				<p class="text-center">
					Todos Direitos Reservados – <strong>LEDS</strong></a> – 2013
				</p>
			</div>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/bootstrap-transition.js"></script>
    <script src="../assets/js/bootstrap-alert.js"></script>
    <script src="../assets/js/bootstrap-modal.js"></script>
    <script src="../assets/js/bootstrap-dropdown.js"></script>
    <script src="../assets/js/bootstrap-scrollspy.js"></script>
    <script src="../assets/js/bootstrap-tab.js"></script>
    <script src="../assets/js/bootstrap-tooltip.js"></script>
    <script src="../assets/js/bootstrap-popover.js"></script>
    <script src="../assets/js/bootstrap-button.js"></script>
    <script src="../assets/js/bootstrap-collapse.js"></script>
    <script src="../assets/js/bootstrap-carousel.js"></script>
    <script src="../assets/js/bootstrap-typeahead.js"></script>

  </body>
</html>